name: CI/CD Impacta - Build go
description: "Build da aplicação Go para aula de CI/CD"

runs:
  using: composite
  steps:
    - name: "Set up Go"
      uses: actions/setup-go@v5
      with:
        go-version: ">=1.15.0"

    - name: "Building..."
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          echo -e "Inicializando build Linux"
          go build ${{ env.FILE_NAME }}.go
        else
          echo -e "Inicializando build Windows"
          GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go
        fi
